In [1]:
import pandas as pd

In [72]:
df= pd.read_csv('FueFem2008_sinuefeff.csv')

ValueError: No columns to parse from file

In [71]:
df.head()

,Estado,SALUD,IMSS-ORD,ISSSTE,IMSS-OP,DIF,PEMEX,SEDENA,SEMAR,Otras,Total
0,Aguascalientes,76,0,0,N.A.,0,N.A.,0,N.A.,3,79
1,Baja California,266,3,0,1,N.A.,N.A.,4,0,29,303
2,Baja California Sur,152,1,1,N.A.,N.A.,N.A.,0,0,N.A.,154
3,Campeche,745,0,0,1,0,0,0,0,0,746
4,Coahuila,59,0,4,22,0,N.A.,0,N.A.,24,109

In [69]:
df['Estado'].unique()

KeyError: 'Estado'

In [64]:
print(u'Estado')

Estado

In [65]:
df

,Estado,SALUD,IMSS-ORD,ISSSTE,IMSS-OP,DIF,PEMEX,SEDENA,SEMAR,Otras,Total
0,Aguascalientes,76,0,0,N.A.,0,N.A.,0,N.A.,3,79
1,Baja California,266,3,0,1,N.A.,N.A.,4,0,29,303
2,Baja California Sur,152,1,1,N.A.,N.A.,N.A.,0,0,N.A.,154
3,Campeche,745,0,0,1,0,0,0,0,0,746
4,Coahuila,59,0,4,22,0,N.A.,0,N.A.,24,109
5,Colima,99,0,1,N.A.,0,N.A.,0,0,0,100
6,Chiapas,130,0,20,26,N.A.,0,2,0,2,180
7,Chihuahua,1 565,9,0,37,N.A.,N.A.,0,N.A.,12,1 623
8,Distrito Federal,539,0,157,0,0,0,33,5,4,738
9,Durango,95,0,0,15,0,N.A.,0,N.A.,1,111
10,Guanajuato,1 065,0,0,0,N.A.,10,9,N.A.,10,1 094
11,Guerrero,297,0,3,3,N.A.,N.A.,2,0,N.A.,305
12,Hidalgo,1 605,0,0,10,38,1,0,N.A.,0,1 654
13,Jalisco,335,2,0,0,22,0,1,0,1 606,1 966
14,México,173,7,3,0,224,N.A.,7,N.A.,7,421
15,Michoacán,980,0,0,44,N.A.,N.A.,2,0,N.A.,1 026
16,Morelos,135,2,1,0,N.A.,N.A.,0,N.A.,N.A.,138
17,Nayarit,762,1,0,17,25,N.A.,0,0,5,810
18,Nuevo León,718,2,0,1,N.A.,0,0,N.A.,108,829
19,Oaxaca,679,0,11,65,42,4,1,1,2,805
20,Puebla,373,6,1,32,0,0,5,N.A.,35,452
21,Querétaro,3 255,3,3,0,0,N.A.,1,N.A.,0,3 262
22,Quintana Roo,251,0,14,N.A.,N.A.,N.A.,0,0,N.A.,265
23,San Luis Potosí,104,5,0,11,N.A.,0,0,N.A.,11,131
24,Sinaloa,195,5,9,66,112,0,2,0,2,391
25,Sonora,165,0,0,0,N.A.,N.A.,1,0,6,172
26,Tabasco,442,0,4,N.A.,N.A.,0,0,0,6,452
27,Tamaulipas,44,0,1,5,2,1,2,0,0,55
28,Tlaxcala,158,0,0,0,0,N.A.,0,N.A.,0,158
29,Veracruz,246,1,6,43,2,2,6,0,N.A.,306
30,Yucatán,956,4,0,41,0,N.A.,0,0,1,1 002
31,Zacatecas,1 896,0,1,21,0,N.A.,0,N.A.,0,1 918
32,TOTAL GLOBAL,18 560,51,240,461,467,18,78,6,1 874,21 755

In [28]:
df.columns

Index(['﻿Estado ', 'SALUD ', 'IMSS-ORD ', 'ISSSTE ', 'IMSS-OP ', 'DIF ',
       'PEMEX ', 'SEDENA ', 'SEMAR ', 'Otras ', 'Total'],
      dtype='object')

In [52]:
print('hi....'+ u'sdf \r hi')

 hi

In [55]:
print('Total')

Total